spring:
  application:
    name: arquiteturaspring
  jpa:
    show_sql: true
  main:
    lazy-initialization: false

app:
  montadora:
    motor-padrao: 130
  config:
    variavel: valor da variavel  x
    valor1: 500